package com.arena.compoundmanagement.service;

import com.arena.compoundmanagement.dto.ComponentRequest;
import com.arena.compoundmanagement.model.EngineeringComponent;
import com.arena.compoundmanagement.model.EngineeringDomain;
import com.arena.compoundmanagement.repository.ComponentRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class ComponentServiceTest {

    @Mock
    private ComponentRepository componentRepository;

    @Mock
    private AuditLogService auditLogService;

    private final ClassificationService classificationService = new ClassificationService();

    @Test
    void createAssignsAutoGeneratedCodeWhenCodeIsEmpty() {
        when(componentRepository.existsByComponentCodeIgnoreCase(anyString())).thenReturn(false);
        when(componentRepository.save(any(EngineeringComponent.class)))
                .thenAnswer(invocation -> {
                    EngineeringComponent component = invocation.getArgument(0);
                    component.setId(99L);
                    return component;
                });

        ComponentService service = new ComponentService(componentRepository, classificationService, auditLogService);

        EngineeringComponent saved = service.create(request(null, "ESP32 Development Module", EngineeringDomain.ECE, 40));

        assertEquals("ECE", saved.getComponentCode().substring(0, 3));
        assertEquals(99L, saved.getId());
        verify(auditLogService).record(any(), anyString(), anyString(), anyString());
    }

    @Test
    void rejectsDuplicateComponentCode() {
        EngineeringComponent existing = new EngineeringComponent();
        existing.setId(1L);
        existing.setComponentCode("ECE-TEST-001");

        when(componentRepository.findByComponentCodeIgnoreCase("ECE-TEST-001"))
                .thenReturn(Optional.of(existing));

        ComponentService service = new ComponentService(componentRepository, classificationService, auditLogService);

        assertThrows(IllegalArgumentException.class,
                () -> service.create(request("ECE-TEST-001", "Duplicated", EngineeringDomain.ECE, 10)));
    }

    private ComponentRequest request(String code, String name, EngineeringDomain domain, int quantity) {
        ComponentRequest request = new ComponentRequest();
        request.setComponentCode(code);
        request.setName(name);
        request.setDiscipline(domain);
        request.setCategory("Embedded & IoT Controllers");
        request.setRegion("Asia-Pacific");
        request.setQuantity(quantity);
        request.setMinimumStockLevel(5);
        request.setMonthlyDemand(10.0);
        request.setLeadTimeDays(15);
        request.setUnitPrice(12.0);
        return request;
    }
}
